### ISSUE TITLE
PascalABC.NET генерирует небезопасный код

### ISSUE THREAD

**Issue by sanyarnd** [sanyarnd/PascalABC.NET-Robocode#6]
```
=========================
Round 1 of 10
=========================
SYSTEM: An error occurred during initialization of PABCRobocode.TestRobot2
SYSTEM: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at PABCRobocode.TestRobot2..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at net.sf.robocode.dotnet.host.proxies.HostingRobotProxy.loadRobotRound()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.VerificationException: Operation could destabilize the runtime.
   at PABCRobocode.TestRobot2..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at net.sf.robocode.dotnet.host.proxies.HostingRobotProxy.loadRobotRound()

```

**Comment by sanyarnd** [comment]
pascalabcnet/pascalabcnet#330
